### ISSUE TITLE
Feedback on page: /guides/v2.2/howdoi/customize-form-configuration.html

### ISSUE THREAD

**Issue by meker12** [magento/devdocs#5040]
# General issue

## Description:

Looks like this page has two titles:  The first is coded as a title; the second as a subtitle.  Subtitle is larger than the title. 

![image](https://user-images.githubusercontent.com/6391769/61835148-3e6d4800-ae40-11e9-9b7b-1352e7842d6c.png)

Is this the way the title and subtitle fields in the metadata are intended to be displayed? 
Or does the metadata need to be cleaned up?

```---
layout: tutorial
group: how-do-i
subgroup:
title: Customize using a modifier class
subtitle: Customize Product Creation Form
menu_node:
level3_subgroup: product-creation-form
menu_order: 3
---
```

## Possible solutions:
- Check the metadata and clean up as needed.

**Comment by keharper** [comment]
@meker12  This is the frontmatter of the REST order processing tutorial

```
layout: tutorial
group: rest-api
title: Step 1. Configure the store
subtitle: Order processing tutorial
return_to:
  title: REST tutorials
  url: rest/tutorials/index.html
menu_order: 1
level3_subgroup: order-tutorial
```

The topic you site isn't using all of the tags it's supposed to have, but `subtitle` is meant to be rendered at the top of every page in the tutorial, with `title` being the standard H1. I wouldn't mind if the subtitle is styled to be smaller, but @belbiy should give his opinion.
