### ISSUE TITLE
Feedback on page: /guides/v2.3/cloud/trouble/troubleshoot-deployment.html

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#5278]
# General issue

## Description:

There was a recent update which made it mandatory to specify version for all services on cloud. All services defined in `.magento.app.yaml` or `.magento/services.yaml` must have a valid version specified or it will break deployment. The deploy will still fail if the configuration is not valid and/or if there is a service in `services.yaml` which does not specify the version.

## Possible solutions:

Add a section about the new requirement in the [Troubleshoot deployment](https://devdocs.magento.com/guides/v2.3/cloud/trouble/troubleshoot-deployment.html) topic.

For example, the version number for `rabbitmq` in the following config is missing:

```
mysql:
    type: mysql:10.0
    disk: 2048

redis:
    type: redis:3.0

elasticsearch52:
    type: elasticsearch:5.2
    disk: 1024

rabbitmq:
    type: rabbitmq
    disk: 1024
```

You must change `type: rabbitmq` to `type: rabbitmq:3.5` and redeploy.

It is `rabbitmq` in this case, but it could be any other service missing the specified version. This could be help resolve a depolyment issue.

## Additional information:

Reported by Magento Support.

This topic is one of many scheduled for migration to the [Magento Help Center](https://support.magento.com). Although we can update existing troubleshooting topics in devdocs prior to migration, it's important that people understand that this type of content belongs on the Help Center per internal content strategy.
