### ISSUE TITLE
Feedback on page: /cloud/project/project-patch.html

### ISSUE THREAD

**Issue by ilima-ebay** [magento/devdocs#8779]
# General issue

## Description:
The indentation of the .magento.env.yaml examples is incorrect. You are currently using 4 spaces but it should be 2 spaces in the below sections:
- [Apply a patch in a local environment](https://devdocs.magento.com/cloud/project/project-patch.html#apply-a-patch-in-a-cloud-environment)
```
stage:     
    build:
        QUALITY_PATCHES:
            - MCTEST-1002             
            - MCTEST-1003
```
- [Apply a patch in a Cloud environment](https://devdocs.magento.com/cloud/project/project-patch.html#apply-a-patch-in-a-cloud-environment)

```
stage:     
    build:
        QUALITY_PATCHES:
            - MCTEST-1002             
            - MCTEST-1003
```
## Possible solutions:
Update indentation in the code snippets
from
```
stage:     
    build:
        QUALITY_PATCHES:
            - MCTEST-1002             
            - MCTEST-1003
```
to
```
stage:     
  build:
    QUALITY_PATCHES:
      - MCTEST-1002             
      - MCTEST-1003
```
## Additional information:
n/a
