### ISSUE TITLE
Improve build and deploy env definitions

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#8815]
# General issue

Feedback on page: /cloud/project/magento-env-yaml.html

Recommend adding a note to these items, in particular ``deploy``:

```
o build—Controls actions in the build phase only. If you do not specify settings in this section, the build phase uses settings from the global section.
o deploy—Controls actions in the deploy phase only. If you do not specify settings in this section, the deploy phase uses settings from the global section.
```

## Possible solutions:

If you have enabled [Configuration Management](https://devdocs.magento.com/cloud/live/sens-data-over.html) after dumping the configurations, you should move the SCD_* variables from the deploy to the build stage.

E.g.,

Before Configuration Management:

```
  deploy:
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      consumers: []
    SCD_STRATEGY: compact
    SCD_MATRIX:
      ...
    REDIS_USE_SLAVE_CONNECTION: 1
```

After enabling Configuration Management, move the SCD_* variables to the build stage:

```
  deploy:
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      consumers: []
    REDIS_USE_SLAVE_CONNECTION: 1
  build:
    SCD_STRATEGY: compact
    SCD_MATRIX:
      ...
```
