### ISSUE TITLE
Fix code block language identifier

### ISSUE THREAD

**Issue by EdOverflow** [magento/devdocs#9101]
# General issue

Topic: /guides/v2.4/security/security-txt.html

## Description:

The example `security.txt` file uses rouge's `bash` syntax highlighting which prepends a `$` symbol. This results in an invalid `security.txt` file.

![image](https://user-images.githubusercontent.com/18099289/130318391-8c54fd7b-2ff4-441c-82ca-a4daeae3b83f.png)

https://github.com/magento/devdocs/blob/9a434591f5e5b5c1c3822efcdb3f9983d118b6d7/src/guides/v2.4/security/security-txt.md#L20-L27

The resulting CSS can be seen below.

```css
.highlighter-rouge.language-bash .rouge-code pre:before {
    display: inline;
    content: "$";
    margin-right: 5px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

## Possible solutions:

I believe rouge supports `plaintext` or `text` for plaintext files that do not have any syntax highlighting. [[1]](https://github.com/rouge-ruby/rouge/blob/442c8f430277889afc6ce0ccbbdbdaec687abc0f/lib/rouge/lexers/plain_text.rb)
