### ISSUE TITLE
Feedback on page: /cloud/env/variables-deploy.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9181]
9# General issue9

## Description:

Adjust the following:

``The following example merges a new value to the existing configuration:``

```
stage:
  deploy:
    ELASTICSUITE_CONFIGURATION:
      indices_settings:
        number_of_shards: 3
        number_of_replicas: 3
      _merge: true
```

## Possible solutions:

Number of replicas should be 2

## Additional information:

There is no circumstance under which the number of replicas should be 3.

It's easier to simply copy and paste the entire thing when advising a customer how to set the configuration, without having to remember to manually correct the value before sending it to the customer
